"""
E10.2 — run the ingestion pipeline over every file in `dumps/` and check it is
handled per E1.4 (graceful degradation, no silent partial load).

    python evidence/broken-dumps/check.py        # runs + rewrites RESULTS.md

For each dump: `normalize()` -> `build_report()` -> the same classification
`_process()` applies (unrecognised / rejected / ok). The outcome must match
`EXPECTED.json`, and the rendered data-quality report must contain each
`must_say` phrase — i.e. the pipeline names the problem, it never loads silently.
"""
from __future__ import annotations

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path[:0] = [os.path.join(ROOT, "src", "api")]

from ingest.core import normalize                        # noqa: E402
from ingest.dq import build_report, render_markdown      # noqa: E402

DUMPS = os.path.join(HERE, "dumps")
_CONF_RANK = {"Low": 0, "Medium": 1, "High": 2}


def _classify(res) -> tuple[str, int]:
    """Mirror ingest.functions._process: (status, rows_loaded)."""
    hard = [i for i in res.issues if i.level == "error"]
    if res.table is None:
        return "unrecognised", 0
    if hard:
        return "rejected", 0
    return "ok", len(res.rows)


def run() -> dict:
    expected = {k: v for k, v in json.load(
        open(os.path.join(HERE, "EXPECTED.json"), encoding="utf-8")).items()
        if not k.startswith("_")}

    results = []
    for name in sorted(expected):
        exp = expected[name]
        data = open(os.path.join(DUMPS, name), "rb").read()
        res = normalize(name, data)
        rep = build_report([res])
        md = render_markdown(rep).lower()
        status, loaded = _classify(res)

        checks = {
            "status": status == exp["status"],
            "table": (res.table or None) == exp["table"],
            "rows_loaded": loaded == exp["rows_loaded"],
            "confidence": _CONF_RANK[rep["confidence_hint"]] <= _CONF_RANK[exp["min_confidence"]],
            "names_the_problem": all(p.lower() in md for p in exp["must_say"]),
        }
        missing_phrases = [p for p in exp["must_say"] if p.lower() not in md]
        results.append({
            "file": name, "failure_mode": exp["failure_mode"],
            "expected_status": exp["status"], "actual_status": status,
            "table": res.table, "rows_loaded": loaded,
            "confidence": rep["confidence_hint"],
            "findings": rep["findings"],
            "checks": checks, "missing_phrases": missing_phrases,
            "ok": all(checks.values()),
        })

    return {"corpus_size": len(results), "all_handled": all(r["ok"] for r in results),
            "results": results}


def _md(res: dict) -> str:
    L = ["# E10.2 — Broken-dump corpus",
         "",
         "_Generated by `evidence/broken-dumps/check.py` — deterministic, no network._",
         "",
         f"{res['corpus_size']} deliberately damaged inventory files in [`dumps/`](dumps/). "
         "Each is run through the real ingestion pipeline (`normalize` -> `build_report` -> "
         "the `_process` classifier). **E1.4** requires that a damaged file is either not "
         "loaded (`unrecognised` / `rejected`) or loaded with the gap named in the "
         "data-quality report — never a silent partial load.",
         "",
         f"**Result: {'PASS' if res['all_handled'] else 'FAIL'}** — "
         f"{sum(r['ok'] for r in res['results'])}/{res['corpus_size']} files handled per E1.4.",
         "",
         "| # | File | Failure mode | Outcome | Rows loaded | Confidence |",
         "|--|---|---|---|--:|:--:|"]
    for i, r in enumerate(res["results"], 1):
        verdict = "✅" if r["ok"] else "❌"
        L.append(f"| {i} | `{r['file']}` | {r['failure_mode']} | "
                 f"{verdict} {r['actual_status']}"
                 + (f" ({r['table']})" if r["table"] else "")
                 + f" | {r['rows_loaded']} | {r['confidence']} |")
    L += ["", "## Per-file detail", ""]
    for r in res["results"]:
        L += [f"### `{r['file']}`",
              f"*{r['failure_mode']}*", "",
              f"- classified **{r['actual_status']}** "
              f"(expected `{r['expected_status']}`), {r['rows_loaded']} rows to SQL, "
              f"confidence **{r['confidence']}**"]
        if not r["ok"]:
            L.append(f"- ⚠️ FAILED checks: "
                     + ", ".join(k for k, v in r["checks"].items() if not v)
                     + (f"; missing phrases: {r['missing_phrases']}" if r["missing_phrases"] else ""))
        L.append("- data-quality report says:")
        for f in r["findings"]:
            L.append(f"  - {f}")
        L.append("")
    L += ["## Reading this",
          "",
          "`unrecognised` = no source profile matched; the file is logged and skipped. "
          "`rejected` = a profile matched but a required column is absent on every row; "
          "nothing loads. `ok` = the rows loaded, and the confidence + findings above are "
          "what the pre-sales team and the client see — the estimate proceeds at a stated, "
          "lowered confidence with an explicit \"ask the client for X\" list.",
          ""]
    return "\n".join(L)


def main() -> int:
    res = run()
    with open(os.path.join(HERE, "RESULTS.md"), "w", encoding="utf-8", newline="\n") as fh:
        fh.write(_md(res))
    for r in res["results"]:
        print(f"{'ok ' if r['ok'] else 'FAIL'} {r['file']:42s} "
              f"{r['actual_status']:12s} rows={r['rows_loaded']:2d} {r['confidence']}")
    print(f"\n{'ALL HANDLED PER E1.4' if res['all_handled'] else 'SOME FILES MISHANDLED'}")
    return 0 if res["all_handled"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
