"""
E10.1 back-test — three independent costing methods over three synthetic estates.

    python evidence/backtest/backtest.py          # runs + rewrites RESULTS.md

For each estate the monthly Azure run-rate is estimated three ways (see
methods.py). The estate passes if the spread — (max - min) / median — is within
TOLERANCE. `run()` returns the structured result; `main()` writes RESULTS.md.

Deterministic: same estates, same synthetic price books, same numbers every run.
"""
from __future__ import annotations

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path[:0] = [os.path.join(ROOT, "src", "api"), os.path.join(ROOT, "evals"), HERE]

from cost.config import load_config                       # noqa: E402

from estate_gen import PRESETS, build_estate, estate_profile  # noqa: E402
from methods import price_all                              # noqa: E402
from pricebook import books as _books                      # noqa: E402

TOLERANCE = 0.15            # (max - min) / median across the three methods
PRICE_DATE = "2026-06-01"


def _spread(values: list[float]) -> float:
    import statistics
    med = statistics.median(values)
    return (max(values) - min(values)) / med if med else 0.0


def _variance_notes(estate_prof: dict, methods: list[dict]) -> list[str]:
    by = {m["method"]: m for m in methods}
    eng = by["engine"]
    hi = max(methods, key=lambda m: m["monthly"])
    lo = min(methods, key=lambda m: m["monthly"])
    compute_share = round(100 * eng["compute_monthly"] / eng["monthly"])
    out = [f"Highest **{hi['method']}** (${hi['monthly']:,.0f}), lowest **{lo['method']}** "
           f"(${lo['monthly']:,.0f}); the difference is entirely in the VM compute line "
           f"({compute_share}% of the total — storage + run-rate extras are shared and damp the spread).",
           "The **engine** sits at or above the other two: it prices the exact right-sized "
           "SKU, so memory-heavy VMs land on the constrained-vCPU E-family at its ~1.28x "
           "premium, which the linear rate and the D/F-based bands only partly capture.",
           "**blended** ($/vCPU x right-sized vCPU) tracks within a few percent because the "
           "estate's right-sized footprint is dominated by the D/F families the rate is "
           "median-derived from; it drifts low on the E-family boxes.",
           "**bands** rounds each VM to a representative SKU priced as the D/F mean at the "
           "band ceiling — close to the engine for D/F workloads, a little low for the "
           "memory-optimised tail (1.15x surcharge vs the engine's full E-family price)."]
    if estate_prof["monitored_pct"] < 60:
        out.append(f"Only {estate_prof['monitored_pct']}% of servers carry utilisation data, "
                   "so the rest are not right-sized down — this lifts all three methods "
                   "equally (no effect on the spread, but the absolute number is soft and "
                   "confidence is Low).")
    return out


def run() -> dict:
    cfg = load_config()
    books = _books()
    estates = []
    for preset in PRESETS:
        est = build_estate(preset)
        prof = estate_profile(est)
        methods = price_all(est, cfg, books)
        vals = [m["monthly"] for m in methods]
        spread = _spread(vals)
        estates.append({
            "preset": preset,
            "profile": prof,
            "methods": methods,
            "spread_pct": round(spread * 100, 1),
            "within_tolerance": spread <= TOLERANCE,
            "median_monthly": round(sorted(vals)[1], 2),
            "variance_notes": _variance_notes(prof, methods),
        })
    return {
        "tolerance_pct": round(TOLERANCE * 100),
        "price_book": "evals/fixtures.py synthetic (deterministic)",
        "estates": estates,
        "all_within_tolerance": all(e["within_tolerance"] for e in estates),
    }


def _md(res: dict) -> str:
    L = ["# E10.1 — Cost-method back-test",
         "",
         "_Generated by `evidence/backtest/backtest.py` — deterministic, no network._",
         "",
         f"Three independent methods estimate the monthly Azure run-rate for each estate "
         f"(see [`methods.py`](methods.py)). An estate **passes** when the spread "
         f"`(max − min) / median` is within **±{res['tolerance_pct']}%**.",
         "",
         f"**Result: {'PASS' if res['all_within_tolerance'] else 'FAIL'}** — "
         f"{sum(e['within_tolerance'] for e in res['estates'])}/{len(res['estates'])} estates "
         f"inside ±{res['tolerance_pct']}%.",
         "",
         "| Estate | Servers | vCPU | Monitored | engine | blended | bands | Spread | Verdict |",
         "|---|--:|--:|--:|--:|--:|--:|--:|:--:|"]
    for e in res["estates"]:
        m = {x["method"]: x["monthly"] for x in e["methods"]}
        p = e["profile"]
        L.append(f"| {e['preset']} | {p['servers']} | {p['total_vcpu']:,} | "
                 f"{p['monitored_pct']}% | ${m['engine']:,.0f} | ${m['blended']:,.0f} | "
                 f"${m['bands']:,.0f} | {e['spread_pct']}% | "
                 f"{'✅' if e['within_tolerance'] else '❌'} |")
    L += ["", "All figures are USD/month, 1-year reserved at the configured coverage, "
          "Azure Hybrid Benefit on Windows, region per estate.", ""]
    for e in res["estates"]:
        p = e["profile"]
        L += [f"## {e['preset']}", "",
              f"{p['servers']} servers ({p['powered_on']} powered on) · {p['applications']} "
              f"applications · {p['total_vcpu']:,} vCPU · {p['total_ram_gb']:,} GB RAM · "
              f"{p['storage_volumes']} storage volumes · compliance: "
              f"{', '.join(p['compliance']) or 'none'} · region {p['region']}", ""]
        L.append("| Method | Compute | Storage | Extras | **Total / mo** |")
        L.append("|---|--:|--:|--:|--:|")
        for x in e["methods"]:
            L.append(f"| {x['method']} | ${x['compute_monthly']:,.0f} | "
                     f"${x['storage_monthly']:,.0f} | ${x['extras_monthly']:,.0f} | "
                     f"**${x['monthly']:,.0f}** |")
        L.append("")
        for x in e["methods"]:
            if x.get("note"):
                L.append(f"- _{x['method']}_: {x['note']}")
        L += ["", f"**Spread {e['spread_pct']}%** "
              f"({'within' if e['within_tolerance'] else 'outside'} ±{res['tolerance_pct']}%). "
              "Variance analysis:"]
        for n in e["variance_notes"]:
            L.append(f"- {n}")
        L.append("")
    L += ["## Reading this",
          "",
          "The three methods share the right-sized target footprint, the storage cost and "
          "the run-rate extras; only the **VM compute pricing** differs — catalogue SKU, "
          "linear $/vCPU, and T-shirt bands. Agreement within ±%d%% means the headline "
          "run-rate is a property of the estate, not of the SKU catalogue or the "
          "reservation model. It is **not** a claim of real-world price accuracy — that is "
          "the province of the live Pricing-Calculator POE (E11.16) and the quarterly "
          "price re-benchmark (S2)." % res["tolerance_pct"],
          ""]
    return "\n".join(L)


def main() -> int:
    res = run()
    with open(os.path.join(HERE, "RESULTS.md"), "w", encoding="utf-8", newline="\n") as fh:
        fh.write(_md(res))
    for e in res["estates"]:
        print(f"{e['preset']:12s} spread {e['spread_pct']:5.1f}%  "
              f"{'PASS' if e['within_tolerance'] else 'FAIL'}  "
              f"(engine ${e['methods'][0]['monthly']:,.0f}/mo)")
    print(f"\n{'ALL WITHIN TOLERANCE' if res['all_within_tolerance'] else 'OUT OF TOLERANCE'} "
          f"(±{res['tolerance_pct']}%)")
    return 0 if res["all_within_tolerance"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
